---
title: "AnVIL Demos"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: Description about Course/Book.
favicon: assets/AnVIL_style/anvil_favicon.ico
---


# About this Series {-}

Welcome to our series of demos introducing the Genomic Data Science Analysis, Visualization, and Informatics Lab-space (AnVIL) of the National Human Genome Research Institute (NHGRI). [The AnVIL](https://anvilproject.org/) is a cloud-based platform designed to provide researchers with secure and controlled access to genomic data, as well as tools for analysis and visualization.

With the increasing availability of genomic data, there is a growing need for efficient and effective tools for data analysis and interpretation. The AnVIL platform addresses this need by providing researchers with easy access to a growing collection of genomic data, as well as powerful tools for analysis and visualization. Our series of demos will guide you through the various features of the AnVIL platform, and show you how it can help you to accelerate your research and make new discoveries in the field of genomics.

Whether you are new to the field of genomics or an experienced researcher, these demos will provide you with valuable insights into the AnVIL platform and its capabilities. We look forward to helping you unlock the full potential of genomic data science through the AnVIL platform. Learn more about AnVIL by visiting https://anvilproject.org or reading the [article in Cell Genomics](https://www.sciencedirect.com/science/article/pii/S2666979X21001063).

<!-- ## Upcoming AnVIL Events {-} -->

<!-- We'd love to see you at an upcoming event! Here are a few upcoming events that might meet your training needs: -->

<!-- ```{r, echo = FALSE, message = FALSE, warning = FALSE} -->
<!-- source("scripts/render_events.R") -->

<!-- knitr::kable(make_events_table(), format = "html") -->
<!-- ``` -->

## AnVIL Monthly Demos  {-}

Collection of monthly AnVIL Demo recordings on YouTube:

```{r echo=FALSE, message = FALSE, warning = FALSE}
library(rvest)
library(stringr)
rendered_tables <- read_html("https://raw.githubusercontent.com/fhdsl/AnVIL_Collection/refs/heads/main/docs/index.md") %>% html_table() # returns a list of tibbles of the tables

# using lapply to look at all the tables in the list from rvest
## this expects that every Demos youtube video will have the word "Demos" in the title (first column)
## Compares total rows vs rows containing "Demos" in first column, then selects this index from all tables
## unlist together with which grabs the index of the table that has the Demos in it (meets the assumption of every title containing the word "Demos")
which_table <- which(unlist(
                lapply(1:length(rendered_tables),
                       function(i) 
                       nrow(rendered_tables[[i]]) == 
                         sum(str_detect(unlist(rendered_tables[[i]][, 1]), "Demos"))
                )
               ))

knitr::kable(rendered_tables[[which_table]], format = "html")
```

## AnVIL Collection {-}

Please check out our full collection of AnVIL and related resources: https://hutchdatascience.org/AnVIL_Collection/
